ml/urls.py
from django.urls import path
import ml.views as ml_views
import ml.api as ml_api

app_name = "website"

urlpatterns = [
    path("upload-file/", ml_views.upload_file, name="upload-file"),
    path(
        "sales-forecast/", ml_views.SalesForecastView.as_view(), name="sales-forecast"
    ),
    path(
        "customer-segmentation/",
        ml_views.CustomerSegmentationView.as_view(),
        name="customer-segmentation",
    ),
    # =============
    # API
    # =============
    path(
        "api/sales-forecast/",
        ml_api.SalesForecastAPI.as_view(),
        name="api-sales-forecast",
    ),
    path(
        "api/customer-segmentation/",
        ml_api.CustomerSegmentationAPI.as_view(),
        name="api-sales-forecast",
    ),
]

sales_forecasting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('ml.urls')),
]

ml/models.py
from django.db import models


# Create your models here.
class FileModel(models.Model):
    file = models.FileField()

    create_date = models.DateTimeField(auto_now_add=True)

ml/views.py
from django.views import generic
from django.views.decorators.http import require_POST
from django.http import HttpResponse, HttpResponseBadRequest
from src.pipeline import predict_pipeline


from ml.models import FileModel
from ml.pipline import customer_pipeline


@require_POST
def upload_file(request):
    if request.FILES:
        file = request.FILES["file"]
        file_obj = FileModel.objects.create(file=file)
        return HttpResponse(file_obj.id)
    return HttpResponseBadRequest()


# @require_POST
# def run_forcasting(request):
#     print(request.POST)
#     if file_id := request.POST.get("file"):
#     return (reverse("website:home"))


class SalesForecastView(generic.TemplateView):
    template_name = "sales_forecasting/index.html"

    def post(self, request, *args, **kwargs):
        file_id = request.POST.get("file")
        if not file_id:
            return HttpResponseBadRequest()
        file_model = FileModel.objects.get(id=file_id)
        print(file_model.file.path)
        forcast_data = predict_pipeline.predict(file_model.file.path)
        context = self.get_context_data()
        context["data"] = forcast_data.to_dict(index=True)
        return self.render_to_response(context)


class CustomerSegmentationView(generic.TemplateView):
    template_name = "customer_segmentation/index.html"

    def post(self, request, *args, **kwargs):
        file_id = request.POST.get("file")
        if not file_id:
            return HttpResponseBadRequest()
        file_model = FileModel.objects.get(id=file_id)
        forcast_data = customer_pipeline.predict(file_model.file.path)
        data = {}
        print(forcast_data)
        counter = 0
        for index, item in forcast_data.iterrows():
            # print(item)
            counter += 1
            if counter > 800:
                break
            if not data.get(item["cluster_pca"]):
                data[item["cluster_pca"]] = []
            data[item["cluster_pca"]].append(
                [round(item["PURCHASES"], 2), round(item["PAYMENTS"], 2)]
            )

        context = self.get_context_data()
        context["data"] = data
        return self.render_to_response(context)

templates/_partial/footer.html
<footer class="footer footer-transparent d-print-none">
          <div class="container-xl">
            <div class="row text-center align-items-center flex-row-reverse">
              <div class="col-lg-auto ms-lg-auto">
                <ul class="list-inline list-inline-dots mb-0">
                  <li class="list-inline-item"><a href="https://tabler.io/docs" target="_blank" class="link-secondary" rel="noopener">Documentation</a></li>
                  <li class="list-inline-item"><a href="./license.html" class="link-secondary">License</a></li>
                  <li class="list-inline-item"><a href="https://github.com/tabler/tabler" target="_blank" class="link-secondary" rel="noopener">Source code</a></li>
                  <li class="list-inline-item">
                    <a href="https://github.com/sponsors/codecalm" target="_blank" class="link-secondary" rel="noopener">
                      <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon text-pink icon-filled icon-inline" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572"></path></svg>
                      Sponsor
                    </a>
                  </li>
                </ul>
              </div>
              <div class="col-12 col-lg-auto mt-3 mt-lg-0">
                <ul class="list-inline list-inline-dots mb-0">
                  <li class="list-inline-item">
                    Copyright © 2023
                    <a href="." class="link-secondary">Tabler</a>.
                    All rights reserved.
                  </li>
                  <li class="list-inline-item">
                    <a href="./changelog.html" class="link-secondary" rel="noopener">
                      v1.0.0-beta20
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </footer>

templates/_partial/full_header.html
{% load static %}
<header class="navbar navbar-expand-md d-print-none bg-white">
        <div class="container-xl">

          <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
            <a href="" class="d-flex justify-content-center align-items-center">
              <img src="{% static 'images/S.png' %}" width="110" height="32" alt="Tabler" class="navbar-brand-image">
              <span class="fs-2 ms-2">Sales forcast</span>
            </a>
          </h1>
    
        </div>
      </header>

templates/base.html
{% extends "template.html" %}
{% load static %}

{% block css_link %}
    <link rel="stylesheet" href="{% static 'css/vendor/tabler.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/website.css' %}">
{% endblock %}

{% block body %}
<div class="page">
    {% block header %}
        {% include "_partial/full_header.html" %}
    {% endblock header %}

    <div class="page-wrapper">
        {% block page %}
        {% block page_header %}{% endblock %}
        <div class="page-body">
            {% block page_body %}
            {% endblock %}
            {% block footer %}
            {% include '_partial/footer.html' %}
            {% endblock %}
        </div>
        {% endblock %}
    </div>
</div>
{% block model %}
{% endblock model %}


{% endblock body %}


{% block js %}
<script src="{% static 'js/tabler.min.js' %}"></script>
<script src="{% static 'js/website.js' %}"></script>
{% endblock %}

templates/customer_segmentation/index.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css_link %}
  <link rel="stylesheet" href="{% static 'css/vendor/apexcharts.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/vendor/filepond.css' %}" />
  <link rel="stylesheet" href="{% static 'css/vendor/filepond-plugin-image-preview.min.css' %}" />
{% endblock %}

{% block header %}
  <header class="navbar navbar-expand-md d-print-none bg-white">
    <div class="container-xl">
      <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
        <a href="" class="d-flex justify-content-center align-items-center">
          <img src="{% static 'images/logo.png' %}" width="110" height="32" alt="Tabler" class="navbar-brand-image" />
          <span class="fs-2 ms-2">Customer Segmentation</span>
        </a>
      </h1>
    </div>
  </header>
{% endblock %}

{% block page_body %}
  <div class="container-xl">
    <div class="card mb-2">
      <div class="card-body">
        <h3 class="card-title">Basic Usage</h3>
        <form class="dropzone dz-clickable" id="dropzone-default" action="" method="post" autocomplete="off" novalidate="">
          {% csrf_token %}
          <input type="file" name="file" />
          <div class="d-flex justify-content-end">
            <input type="submit" class="btn btn-primary" value="Run forcasting" accept=".csv" />
          </div>
        </form>
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <div id="chart" class="chart-lg"></div>
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_js %}
  <script src="{% static 'js/filepond-plugin-file-validate-type.min.js' %}"></script>
  <script src="{% static 'js/filepond.js' %}"></script>
  <script src="{% static 'js/apexcharts.min.js' %}"></script>

  <script>
    FilePond.registerPlugin(FilePondPluginFileValidateType)
    FilePond.create(document.querySelector('input[type=file]'), {
      acceptedFileTypes: ['text/csv'],
      server: {
        url: "{% url 'website:upload-file' %}",
        headers: {
          'X-CSRFTOKEN': '{{ csrf_token }}'
        }
      }
    })
  </script>
  {% if data %}
  <script>
    var options = {
      series: [
          {% for cluster_id, cluster  in data.items %}
          {name: 'SAMPLE {{cluster_id}}',
          data: {{cluster}}},
          {% endfor %}
      ],
      chart: {
        height: 350,
        type: 'scatter',
        zoom: {
          enabled: true,
          type: 'xy'
        }
      },
      xaxis: {
        tickAmount: 10,
        labels: {
          formatter: function (val) {
            return parseFloat(val).toFixed(1)
          }
        }
      },
      yaxis: {
        tickAmount: 7
      }
    }
    
    var chart = new ApexCharts(document.querySelector('#chart'), options)
    chart.render()
  </script>
  {% endif %}
{% endblock %}

templates/sales_forecasting/index.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css_link %}
  <link rel="stylesheet" href="{% static 'css/vendor/apexcharts.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/vendor/filepond.css' %}" />
  <link rel="stylesheet" href="{% static 'css/vendor/filepond-plugin-image-preview.min.css' %}" />
{% endblock %}

{% block header %}
  <header class="navbar navbar-expand-md d-print-none bg-white">
    <div class="container-xl">
      <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
        <a href="" class="d-flex justify-content-center align-items-center">
          <img src="{% static 'images/S.png' %}" width="110" height="32" alt="Tabler" class="navbar-brand-image" />
          <span class="fs-2 ms-2">Sales forcast</span>
        </a>
      </h1>
    </div>
  </header>
{% endblock %}



{% block page_body %}

  <div class="container-xl">
    <div class="card mb-2">
      <div class="card-body">
        <h3 class="card-title">Basic Usage</h3>
        <form class="dropzone dz-clickable" id="dropzone-default" action="" method="post" autocomplete="off" novalidate="">
          {% csrf_token %}
          <input type="file" name="file" />
          <div class="d-flex justify-content-end">
            <input type="submit" class="btn btn-primary" value="Run forcasting" accept=".csv" />
          </div>
        </form>
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <div id="chart-demo-line" class="chart-lg"></div>
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_js %}
  <script src="{% static 'js/filepond-plugin-file-validate-type.min.js' %}"></script>
  <script src="{% static 'js/filepond.js' %}"></script>
  <script src="{% static 'js/apexcharts.min.js' %}"></script>

  <script>
    FilePond.registerPlugin(FilePondPluginFileValidateType)
    FilePond.create(document.querySelector('input[type=file]'), {
      acceptedFileTypes: ['text/csv'],
      server: {
        url: "{% url 'website:upload-file' %}",
        headers: {
          'X-CSRFTOKEN': '{{ csrf_token }}'
        }
      }
    })
  </script>
  {% if data %}
  <script>
    document.addEventListener("DOMContentLoaded", function() {
        window.ApexCharts && (new ApexCharts(document.getElementById('chart-demo-line'), {
          chart: {
            type: "line",
            fontFamily: 'inherit',
            height: 240,
            parentHeightOffset: 0,
            toolbar: {
              show: false,
            },
            animations: {
              enabled: false
            },
          },
          fill: {
            opacity: 1,
          },
          stroke: {
            width: 2,
            lineCap: "round",
            curve: "straight",
          },
          series: [{
            name: "Real data",
            data: [
            {% for index, data in data.Actual.items %} 
                {{data}},
           {% endfor %}
            ]
          }, {
            name: "Forcest data",
            data: [
            {% for index, data in data.Predicted.items %} 
            {{data|get_digit:0}},
            {% endfor %}
            ]
          }],
          tooltip: {
            theme: 'dark'
          },
          grid: {
            padding: {
              top: -20,
              right: 0,
              left: -4,
              bottom: -4
            },
            strokeDashArray: 4,
          },
          xaxis: {
            labels: {
              padding: 0,
            },
            tooltip: {
              enabled: false
            },
            type: 'datetime',
          },
          yaxis: {
            labels: {
              padding: 4
            },
          },
          labels: [
          {% for index, date in data.date.items %} 
            "{{date}}",
           {% endfor %}
          ],
          colors: [tabler.getColor("blue"), tabler.getColor("red")],
          legend: {
            show: true,
            position: 'bottom',
            offsetY: 12,
            markers: {
              width: 10,
              height: 10,
              radius: 100,
            },
            itemMargin: {
              horizontal: 8,
              vertical: 8
            },
          },
        })).render();
      });
  </script>
  {% endif %}
{% endblock %}

templates/template.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{{page_description}}">
        <title>{{page_title}}</title>

        {% block meta_content %}
        {% endblock meta_content %}

        {% block favicon %}
        {% endblock favicon %}

        {% block css_link %}
        {% endblock css_link %}

        {% block extra_css_link %}
        {% endblock extra_css_link %}

        {% block css_style %}
        {% endblock css_style %}
    </head>


    <body >
        {% block body %}{% endblock body %}
        {% block models %}{% endblock %}
        {% block js %}{% endblock js %}
        {% block extra_js %}{% endblock extra_js %}
    </body>

</html>